# Generated by Django 4.2.2 on 2023-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('course', '0001_initial'),
        ('subject', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Period',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=40)),
                ('start_time_period', models.DateField()),
                ('end_time_period', models.DateField()),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'Academic_Period',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(db_column='section_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('period', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, to='section.academic_period')),
                ('professor_rut', models.ForeignKey(db_column='professor_rut', on_delete=django.db.models.deletion.CASCADE, related_name='professor_sections', to='professor.professor')),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'section',
            },
        ),
    ]
