# Generated by Django 4.2.2 on 2023-10-20 15:10

import backend.apps.shared_files.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Publicado', 'Publicado'), ('Oculto', 'Oculto')], default='Publicado', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=backend.apps.shared_files.models.file_directory_path)),
                ('status', models.CharField(choices=[('Publicado', 'Publicado'), ('Oculto', 'Oculto')], default='Publicado', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_files.folder')),
            ],
        ),
    ]
