# Generated by Django 4.2.2 on 2023-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='color',
            field=models.CharField(default='blue', max_length=255),
        ),
    ]
