# Generated by Django 4.2.2 on 2023-10-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_observations',
            fields=[
                ('id_observation', models.AutoField(db_column='id_observation', primary_key=True, serialize=False)),
                ('type_observation', models.CharField(choices=[('positiva', 'positiva'), ('negativa', 'negativa')], max_length=50, verbose_name='Tipo de Observación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True)),
                ('id_schedule', models.ForeignKey(db_column='id_schedule', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule', verbose_name='Horario')),
                ('rut_student', models.ForeignKey(db_column='rut_student', on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Observación del Estudiante',
                'verbose_name_plural': 'Observaciones de los Estudiantes',
                'db_table': 'student_observations',
            },
        ),
    ]
