# Generated by Django 4.2.2 on 2023-10-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_school'),
        ('guardian', '0002_guardian_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_times',
            fields=[
                ('id_available_time', models.BigAutoField(db_column='id_available_time', primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')])),
                ('start_time_block', models.TimeField()),
                ('end_time_block', models.TimeField()),
                ('professor_rut', models.ForeignKey(db_column='professor_rut', on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
            options={
                'verbose_name': 'Horario disponible',
                'verbose_name_plural': 'Horarios disponibles',
                'db_table': 'Available_times',
            },
        ),
        migrations.CreateModel(
            name='Meeting_request',
            fields=[
                ('id_meeting_request', models.BigAutoField(db_column='id_meeting_request', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Confirmada'), ('0', 'Rechazada')], max_length=1)),
                ('guardian_rut', models.ForeignKey(db_column='guardian_rut', on_delete=django.db.models.deletion.CASCADE, to='guardian.guardian')),
                ('id_available_time', models.ForeignKey(db_column='id_available_time', on_delete=django.db.models.deletion.CASCADE, to='guardian.available_times')),
            ],
            options={
                'verbose_name': 'Solicitud de reunión',
                'verbose_name_plural': 'Solicitudes de reunión',
                'db_table': 'Meeting_request',
            },
        ),
    ]
