# Generated by Django 4.2.2 on 2023-10-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        ('guardian', '0004_available_times_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_times',
            name='professor_rut',
        ),
        migrations.AddField(
            model_name='available_times',
            name='section_id',
            field=models.ForeignKey(db_column='section_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
            preserve_default=False,
        ),
    ]
