# Generated by Django 4.2.2 on 2023-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0005_remove_available_times_professor_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_request',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
