# Generated by Django 4.2.2 on 2023-11-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_school'),
        ('guardian', '0006_meeting_request_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_times',
            name='section_id',
        ),
        migrations.AddField(
            model_name='available_times',
            name='professor_rut',
            field=models.ForeignKey(db_column='professor_rut', default='00000000-0', on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
            preserve_default=False,
        ),
    ]
