# Generated by Django 4.2.2 on 2023-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0007_remove_available_times_section_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_request',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
