# Generated by Django 4.2.2 on 2023-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0008_meeting_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_request',
            name='status',
            field=models.CharField(choices=[('0', 'Rechazada'), ('1', 'Confirmada'), ('2', 'En espera')], default='2', max_length=1),
        ),
    ]
