# Generated by Django 4.2.2 on 2023-11-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0010_rename_date_meeting_request_dateselected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_request',
            name='dateSelected',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting_request',
            name='timeSelected',
            field=models.TimeField(default=datetime.time(13, 33, 46, 62389)),
        ),
    ]
