# Generated by Django 4.2.2 on 2023-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0012_alter_meeting_request_timeselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_request',
            name='timeSelected',
            field=models.TimeField(),
        ),
    ]
