# Generated by Django 4.2.2 on 2023-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Borrador'), (3, 'Bloqueado')], default=1),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
    ]
