GET http://127.0.0.1:8000/api/course/utp-info/1/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAwMjYwMDU5LCJpYXQiOjE2OTk2NTUyNTksImp0aSI6IjFmMzkzNjJiMmVkOTQ1YWE4MGFkNjVhM2Y0MDA1NWYyIiwidXNlcl9pZCI6Miwicm9sIjoiVVRQIiwiZW1haWwiOiJ1dHBwcnVlYmFAZ21haWwuY29tIiwiaXNfc3RhZmYiOmZhbHNlfQ.qiOoLUwrC81mxTHmSYrNPGctLB-DuEIJTvC9HRZIweM
