# Generated by Django 4.2.2 on 2023-10-28 02:34

import backend.apps.medical_certificate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_school'),
        ('guardian', '0002_guardian_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Oculto')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=backend.apps.medical_certificate.models.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardian.guardian')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
