# Generated by Django 4.2.2 on 2023-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weighted_average',
            fields=[
                ('id_weighted_average', models.AutoField(db_column='id_weighted_average', primary_key=True, serialize=False)),
                ('weighted_average', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ponderación',
                'verbose_name_plural': 'Ponderaciones',
                'db_table': 'weighted_average',
            },
        ),
    ]
