# Generated by Django 4.2.2 on 2023-10-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('student_rut', models.ForeignKey(db_column='student_rut', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'seccion estudiante',
                'verbose_name_plural': 'seccion estudiantes',
                'db_table': 'student_section',
            },
        ),
    ]
