# Generated by Django 4.2.2 on 2023-10-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('section', '0001_initial'),
        ('weighted_average', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_grades',
            fields=[
                ('id_student_grades', models.AutoField(db_column='id_student_grades', primary_key=True, serialize=False)),
                ('student_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Calificaciones')),
                ('coefficient', models.IntegerField(default=1, verbose_name='Coeficiente')),
                ('is_active', models.BooleanField(default=True)),
                ('id_weighted_average', models.ForeignKey(db_column='id_weighted_average', on_delete=django.db.models.deletion.CASCADE, to='weighted_average.weighted_average')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('student_rut', models.ForeignKey(db_column='student_rut', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Calificación de estudiante',
                'verbose_name_plural': 'Calificaciones de los estudiantes',
                'db_table': 'student_grade',
            },
        ),
    ]
