# Generated by Django 4.2.2 on 2023-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('schedule', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAttendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='attendance_id', primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0)),
                ('full_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('professor_rut', models.ForeignKey(db_column='professor_rut', on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
                ('schedule', models.ForeignKey(db_column='schedule', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Asistencia de profesor',
                'verbose_name_plural': 'Asistencia de profesores',
                'db_table': 'professor_attendance',
            },
        ),
    ]
