# Generated by Django 4.2.2 on 2023-11-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('anuncio', 'Anuncio'), ('discusion', 'Discusión'), ('sugerencias', 'Sugerencias'), ('off-topic', 'Off-Topic'), ('apoderado', 'Apoderado')], default='Discusión', max_length=255),
        ),
    ]
