# Generated by Django 4.2.2 on 2023-10-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='attendance_id', primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0)),
                ('full_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_id', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('student_rut', models.ForeignKey(db_column='student_rut', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Asistencia de estudiante',
                'verbose_name_plural': 'Asistencia de estudiantes',
                'db_table': 'student_attendance',
            },
        ),
    ]
